// <auto-generated />
namespace CoTale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class tryingtogoline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryingtogoline));
        
        string IMigrationMetadata.Id
        {
            get { return "202008211844029_trying tog oline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
